name: loops-control
dependencies:
- ipykernel
- ipython
- jupyter
- jupyter_client
- jupyter_console
- jupyter_core
- numpy
- pillow
- pylint
- pytest
- pytest-cov
- python=3.6.*
- pip:
  - fire
  - flake8
  - flake8-docstrings
  - flake8-isort
  - flake8-quotes
  - Flask
  - Flask-Cors
  - Flask-Dance
  - marshmallow
  - msgpack-numpy
  - opencv-python
